name: pr_validation

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
  merge_group:

jobs:
  test:
    name: Test-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest,]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: "Install .NET SDK"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - name: "Update release notes and version"
        shell: pwsh
        run: |
          ./build.ps1
      - name: "dotnet pack"
        run: dotnet pack -c Release -o bin/nuget

      - name: "Install templates"
        run: dotnet new install bin/nuget/*.nupkg

      - name: "Test dev templates"
        shell: pwsh
        run: |
          ./scripts/test-templates.ps1

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            bin/**/*.nupkg